### ISSUE TITLE
ホワイトボックステスト laco

### ISSUE THREAD

**Issue by lacolaco** [sakura818/write-http-server-01#24]
- sample.mp3にブラウザからアクセスするとサーバーが落ちる

```
正常にコネクションできないエラーが発生しました
Exception in thread "main" java.lang.RuntimeException: java.net.SocketException: Broken pipe
```

再生できないmp3ファイルを置いてる？

- resourcesの外のファイルにアクセスできる

```
> telnet localhost 8080
Trying ::1...
Connected to localhost.
Escape character is '^]'.
GET /../../../README.md HTTP/1.1
```

- `http://localhost:8080/dummyDirectory` にアクセスすると落ちる

```
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: src/main/resources/dummyDirectory (Is a directory)
```

ディレクトリに末尾 `/`なしでアクセスされたときに死ぬっぽい

- `http://localhost:8080/?foo=bar` が404になる

クエリストリングが付いただけでindex.htmlが見えなくなる。 `http://localhost:8080/index.html?foo=bar` でも同じ

- FirefoxとChromeで交互にすばやくリクエストを送るとサーバーが落ちる

```
Exception in thread "main" java.lang.NullPointerException
        at jp.co.topgate.sugawara.web.HttpResponseMessageHeaderBuilder.extractExtension(HttpResponseMessageHeaderBuilder.java:112)
        at jp.co.topgate.sugawara.web.HttpResponseMessageHeaderBuilder.catchContentType(HttpResponseMessageHeaderBuilder.java:98)
        at jp.co.topgate.sugawara.web.HttpResponseMessageHeaderBuilder.createEntityHeader(HttpResponseMessageHeaderBuilder.java:85)
        at jp.co.topgate.sugawara.web.HttpResponseMessageHeaderBuilder.build(HttpResponseMessageHeaderBuilder.java:42)
        at jp.co.topgate.sugawara.web.HttpResponse.createHttpResponseContent(HttpResponse.java:44)
        at jp.co.topgate.sugawara.web.HttpResponse.writeToOutputStream(HttpResponse.java:67)
        at jp.co.topgate.sugawara.web.HttpServer.connect(HttpServer.java:79)
        at jp.co.topgate.sugawara.web.Main.main(Main.java:13)
```

全然わからんけど、複数リクエストがほぼ同時に来たときに、何かファイルの読み込みに影響があるのかもしれない 普通にF5連打しても大丈夫なので原因分かったら直してほしい

**Comment by sakura818** [comment]
- [x] mp3の変更→ダミーファイルのmp3からパブリックドメインのmp3に変更
- [x] resourcesの外のファイルにアクセスできる
- [x] ディレクトリに末尾 /なしでアクセスされたときに死ぬっぽいhttp://localhost:8080/dummyDirectory
- [x] クエストリング
- [ ] FirefoxとChromeで交互にすばやくリクエストを送るとサーバーが落ちる

**Comment by sakura818** [comment]
FirefoxとChromeで交互にすばやくリクエストを送るとサーバーが落ちるに関して、自分の手元でエラーが発生しないので連絡

**Comment by sakura818** [comment]
- [x] クエリ文字列のメソッド　配列の大きさでuripathとクエリ文字列を分割
